<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Twitch_app</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Twitch starting code\**" />
    <Compile Remove="wwwroot\html\**" />
    <Content Remove="Twitch starting code\**" />
    <Content Remove="wwwroot\html\**" />
    <EmbeddedResource Remove="Twitch starting code\**" />
    <EmbeddedResource Remove="wwwroot\html\**" />
    <None Remove="Twitch starting code\**" />
    <None Remove="wwwroot\html\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\backend.js" />
    <Content Remove="wwwroot\js\common.js" />
    <Content Remove="wwwroot\js\config.js" />
    <Content Remove="wwwroot\js\live_config.js" />
    <Content Remove="wwwroot\js\viewer.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\BodyPartPositions.js" />
  </ItemGroup>

</Project>
